theme: jekyll-theme-minimal

exclude: template.md

collections:
  recipes:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "recipes"
    values:
      layout: default